### ISSUE TITLE
Unable to chat with unencrypted clients

### ISSUE THREAD

**Issue by the-unknown** [shtrom/Lurch4Adium#15] opened 2018-10-02 08:19 UTC
I am unable to chat with xmpp clientes that do not support OMEMO. 
If the opposite does not support OMEMO, that chat should be not be encrypted, otherwise the messages will not be readable or received.

**Comment by shtrom** [comment] 2018-10-03 02:03
On Tue 02 Oct 2018 at 01:19:12 -0700, the-unknown wrote:
> I am unable to chat with xmpp clientes that do not support OMEMO.  If
> the opposite does not support OMEMO, that chat should be not be
> encrypted, otherwise the messages will not be readable or received.

Could you give a concrete example to reproduce the issue (e.g., which
clients, which message ordering)?

Note that encryption is per-account, not per-client: if one account is
recorded as supported OMEMO (because one of the clients did at some
point), without intervention, Lurch will keep encrypting for that
client, even though the account may now be only using a non-OMEMO
client.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by the-unknown** [comment] 2018-10-04 12:19
Ok I see where the problem is, now. 
The constellation is like this:

I use multiple clients as I have to use multiple systems:
Conversations on my Phone, Adium on my Workstation (Mac) and Gajim on my Home PC.
My conterpart is my wife, who is on Conversations on her phone, too (OMEMO encrypted), but on her Workstation she uses Pidgin and has not the possibility to install OMEMO/Lurch there, as all 3rd party tools for Pidgin are forbidden for security reasons. 

So usually we have a OMEMO conversation as we usually write on our phones and that works flawlessly.
However when she is at work and I am at work I would like to chat with her. I know, that I have to use a non-OMEMO way to do so. But I have other people in my contact list who are OMEMO encrypted all the time. Lurch4Adium works well with these people. 
So I would need a way to disable encryption for her chat only, while I use Adium. That way I would not need to install a second XMPP client without encryption to just talk to her.

**Comment by shtrom** [comment] 2018-10-04 12:58
Rah, that sucks.

I had to fight with a pretty similar setup recently (Pidgin from PortableApps doesn't play well with Lurch, for some reason I couldn't work out.)

I'm not sure we can do much here, for two reasons:
* Lurch4Adium really is just a integration work of (drumroll) http://github.com/gkdr/lurch, for Adium, and Lurch doesn't expose this sort of control,
* Disabling encryption is a bad solution, having to do it is a failure of operational security.

As it stands, I'm going to close this bug, as there is not much that can be done, or that I would do if I could, in Lurch4Adium.

I'm also going to apologise for that, because I know how much it sucks to be in this situation...

**Closed as completed by shtrom** 2018-10-04 12:58 UTC
