### ISSUE TITLE
A correct support of OMEMO: 12 byte for initilization vector (IV)

### ISSUE THREAD

**Issue by Neustradamus** [shtrom/Lurch4Adium#21] opened 2020-11-27 05:53 UTC
@shtrom: There is a problem in the code of libomemo used by lurch:
- https://github.com/xsf/xeps/pull/894

I have done a patch here:
- https://github.com/gkdr/libomemo/pull/27

Can you find the solution to have a "good" OMEMO in macOS?

Linked to:
- https://github.com/gkdr/libomemo/issues/24
- https://github.com/gkdr/lurch/issues/142
- https://github.com/gkdr/lurch/issues/74

**Comment by Neustradamus** [comment] 2020-12-03 10:35
@shtrom: @gkdr has released a 0.7.0 build of libomemo with the fix...

Thanks in advance.

**Comment by shtrom** [comment] 2020-12-04 03:54
Lurch4Adium only uses libomemo via lurch, so this is dependent on a new Lurch release. I'll close this as duplicate of #20, with a note that we need also need gkdr/lurch#142 to be merged there. Not sure about #74, though.

**Closed as completed by shtrom** 2020-12-04 03:54 UTC

**Comment by Neustradamus** [comment] 2020-12-04 10:31
@shtrom: It will be better to separate libomemo and lurch.
- https://github.com/gkdr/lurch/pull/151

**Comment by shtrom** [comment] 2020-12-04 10:33
I agree, but I'd prefer not to maintain a fork of lurch. As long as libomemo is bundled with lurch, it's easier to track lurch only, rather than trying to unbundle it in this project.
-- 
Olivier Mehani <shtrom@ssji.net>
Sent from my mobile, please excuse my brevity.
