### ISSUE TITLE
XEP-0384: OMEMO Encryption 0.4.0+

### ISSUE THREAD

**Issue by Neustradamus** [shtrom/Lurch4Adium#20] opened 2020-03-26 01:14 UTC
Can you update the XEP-0384: OMEMO Encryption support to 0.4.0+?
- https://xmpp.org/extensions/xep-0384.html

And XEP-0454: OMEMO Media sharing:
- https://xmpp.org/extensions/xep-0454.html

Diff Tool:
- 0.3.0 to current: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/xep-0384.html
- 0.8.3 to current: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.8.3.html&newfile=https://xmpp.org/extensions/xep-0384.html
- 0.8.2 to 0.8.3: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.8.2.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.8.3.html
- 0.8.1 to 0.8.2: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.8.1.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.8.2.html
- 0.8.0 to 0.8.1: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.8.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.8.1.html
- 0.7.0 to 0.8.0: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.7.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.8.0.html
- 0.6.0 to 0.7.0: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.7.0.html
- 0.5.0 to 0.6.0: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.6.0.html
- 0.4.0 to 0.5.0: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html
- 0.3.0 to 0.4.0: http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

PS: Not sure that 0.3.0 was complete before:
- https://xmpp.org/extensions/attic/xep-0384-0.3.0.html

Linked to:
- https://github.com/gkdr/lurch/issues/143

**Comment by shtrom** [comment] 2020-03-30 21:25
@Neustradamus this would supersede #16 (and need an update to #17 when gkdr/lurch#143 is fixed)?

**Comment by Neustradamus** [comment] 2020-03-30 22:59
Yes after your new changes for Adium with last current builds (lurch 0.6.8+carbons 0.2.2) :)

But I think that all people can work for update the main code ^^
- https://github.com/gkdr/lurch
- https://github.com/gkdr/carbons
- https://github.com/gkdr/libomemo

**Comment by Neustradamus** [comment] 2020-03-30 23:16
@shtrom: Yes after your new changes for Adium with last current builds (lurch 0.6.8+carbons 0.2.2) :)

But I think that all people can work for update the main code from @gkdr ^^
- https://github.com/gkdr/lurch
- https://github.com/gkdr/carbons
- https://github.com/gkdr/libomemo

Note: I am not sure that XEP-0384 v0.3.0 was complete before the release of 0.4.0+ which breaks all.

I have seen "dev" branches:
- https://github.com/gkdr/lurch/branches
- https://github.com/gkdr/carbons/branches

**Comment by shtrom** [comment] 2020-12-04 03:54
We'll need to bump lurch when gkdr/lurch#142 and 143 are merged.

**Comment by shtrom** [comment] 2020-12-04 03:56
Actually, this on is a kinda dupe of #16.

**Closed as completed by shtrom** 2020-12-04 03:56 UTC

**Comment by Neustradamus** [comment] 2020-12-04 10:28
@shtrom: No OMEMO 0.4.0+ has been not solved...
Please reopen this ticket.

**Comment by shtrom** [comment] 2020-12-04 10:31
If I understand correctly, this is dependent on a fix getting merged into lurch. As such, this would be solved by an update to #16 when the fix is merged in lurch.
-- 
Olivier Mehani <shtrom@ssji.net>
Sent from my mobile, please excuse my brevity.
